### ISSUE TITLE
Doesn't seem updated for official firmware v.15

### ISSUE THREAD

**Issue by 1lk** [zerter555/garlicOS_Simple_SF2000_THEME#2]
Crashes when viewing "history"

Also didn't like the dark grey color, pure black would be more suitable for the background

Besides, do you really need to put your name on every screen? We know who made the theme :/

**Comment by zerter555** [comment]
Its working on all released  firmware even in May 22 1.5V.

https://github.com/zerter555/garlicOS_Simple_SF2000_THEME/assets/45391351/69fc3840-a903-45b4-887b-6a9b0e662fd3

Also didn't like the dark grey color, pure black would be more suitable for the background
- not an issue, you can edit / do a remix of the theme change color to your preferred style. I'm not gonna tailor make a theme for one specific person(Unless I'm commissioned to or someone donated and like to request a minor change to an already made theme. they can even pitch theme ideas if the concept is interesting and I have the time to make it, huge community request for that kind of theme and I'm interested with the concept of the theme). if you don't know how to make or update existing themes, there's already a compilation site for all info needed to make and update themes.
https://vonmillhausen.github.io/sf2000/

Besides, do you really need to put your name on every screen? We know who made the theme :/
- If you don't like it, then you can remove it yourself. like I said  you can edit / do a remix of the theme I wont mind. no complaints from the rest of the community.

**Comment by zerter555** [comment]
If your still using the cheap SD card that it came with. Try using a better quality SD card with the v1.5 firmware image flashed to it.
its known that sf2000 is picky with SD cards. and cheap ones tend to make the frog load slower, stutter, more frequent fps drops, freeze, crash or even not boot the bios(turning the device on, just stuck in black screen - theres a workaround to try and fix this its on the info compilation site).

**Comment by zerter555** [comment]
@1lk 
![image](https://github.com/zerter555/garlicOS_Simple_SF2000_THEME/assets/45391351/6408a88f-b022-4525-8c0d-927b4aa9dcd9)

if you used the frogtool or tadpole, dev who made it will fix the issue
